CREATE DATABASE IF NOT EXISTS vangari_link
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE vangari_link;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role ENUM('seller','buyer') NOT NULL,

  name VARCHAR(100) NOT NULL,
  shop_name VARCHAR(120) NULL,

  area VARCHAR(60) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,

  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

